### ISSUE TITLE
Commenti duplicati italiano/inglese

### ISSUE THREAD

**Issue by fpoli** [studentisgss/booking#11]
Nei vari file `models.py` ci sono dei commenti scritti sia in inglese che in italiano. C'è da fare un po' di pulizia ed eliminare i commenti in italiano (se quelli in inglese comprendono tutte le informazioni).

**Difficoltà: facile**. Consigliato a chi non ha mai lavorato ad un progetto Python.

È preferibile che la modifica venga fatta in una [_branch_](https://github.com/Kunena/Kunena-Forum/wiki/Create-a-new-branch-with-git-and-manage-branches) separata chiamata `clean_comments`, e che l'integrazione avvenga attraverso l'apertura di una [_pull request_](https://help.github.com/articles/creating-a-pull-request/).

Fatevi sotto! :muscle: :muscle:

**Comment by albesianor** [comment]
Se nessuno si propone a breve lo posso fare io, preferirei però fosse qualcuno senza alcuna esperienza

**Comment by fpoli** [comment]
@albesianor per te sto preparando un'altra issue :wink:

**Comment by albesianor** [comment]
:+1
Il 09/dic/2015 22:08, "Federico" notifications@github.com ha scritto:

**Comment by fpoli** [comment]
Ho preparato un tutorial: [la prima issue](https://github.com/studentisgss/booking/wiki/Tutorial%3A-la-prima-issue)

**Comment by FedericoSold** [comment]
Teoricamente è a posto. Spero di non aver sbagliato nulla.
