### ISSUE TITLE
Pagina delle attività

### ISSUE THREAD

**Issue by fpoli** [studentisgss/booking#12]
Non appena la pull request #10 verrà chiusa ed integrata nel progetto si potrà scrivere la prima pagina, che è stata decisa essere **l'elenco delle attività (importanti) presenti nel database**.

**Difficoltà: media**. Consigliato a chi ha già scritto almeno una view con Django, ma non ha mai lavorato a grandi progetti.

Consegna:
- app da usare: activities
- url per la pagina: `/activities/list`
- template per la pagina: `/activities/templates/activities/list.html`
- il template della pagina deve ereditare dal template `/base/templates/base.html` (aspettare che la pull request venga integrata, basta un link relativo `../base.html`)
- la pagina deve elencare solo le `activities` che hanno l'attributo `important` con valore `True`
- l'elenco delle attività deve riportare il titolo dell'attività e la data di creazione (mese e anno soltanto)
- l'elenco deve essere ordinato alfabeticamente secondo il titolo
- l'elenco delle attività deve visualizzarsi bene anche se ci sono accenti o caratteri strani (`<`, `>`, ...) nel titolo
- se nel lavorare alla issue ci si imbatte in qualche problema (bug, qualcosa che manca, ...), aprire una nuova issue :wink:

**Comment by albesianor** [comment]
Posso provare a farlo io, ma giovedì ho un compitino, quindi probabilmente non riuscirò a fare molto prima di quella data

**Comment by fpoli** [comment]
Sì sì, non c'è problema. Anche altri mi hanno detto che hanno qualche esame in questi giorni

**Comment by dtroletti** [comment]
Un paio di domande:
1. Il model di Activity non comprende la data di creazione, va aggiunta?
2. Il flag important indica le attività in corso nell'anno o altro? Nel caso indichi altro non visualizzerei solo le attività con `important = True` ma tutte.
3. Mettere un campo per un filtro?

**Comment by fpoli** [comment]
1. Ok, ma senza visualizzarlo per forza nel sito. All'utente bastano le date delle prenotazioni.
2. Il flag indica le attività "in evidenza", quindi andrebbero posizionate per prime nellle liste o dovrebbero essere evidenziate in qualche modo. Di default possiamo mostrare solo le attività importanti, mettendo un pulsante "visualizza tutte" per visualizzare anche le non importanti. Forse è più intuitivo usare un flag "archiviato", con esattamente il significato inverso di "importante".
3. Non ho ben presente come verrebbe implementato, per adesso possiamo anche aspettare.

**Comment by dtroletti** [comment]
Risolto nel commit 4a1947aa42e21f182e0096c824600310b8e4c0dc.
