### ISSUE TITLE
Cambiare provider mappe

### ISSUE THREAD

**Issue by FedericoSold** [studentisgss/booking#135]
Passare a Mapbox sia nella pagina di creazione di edifici che in quella di dettaglio aula.

**Comment by dtroletti** [comment]
Ho cambiato per la modifica edificio e messo Mapbox. Per la visualizzazione ho lasciato Google Maps in quanto è molto superiore: visualizza bene l'indirizzo e permette di avere le indicazioni in modo automatico. Mapbox richiederebbe di fare tutto a mano.
Ditemi cosa ne pensate, se va bene apro la pull request.

Vedete il commit a2a87dbca362a55ba5b0ad94aa06310889b91357

**Comment by dtroletti** [comment]
Risolto con #137
