### ISSUE TITLE
Cosa fare per la demo?

### ISSUE THREAD

**Issue by fpoli** [studentisgss/booking#15]
Abbiamo preparato una demo: https://demo-sgss.rhcloud.com/
Viene aggiornata automagicamente! :sparkles: :sparkles: :sparkles:
Ogni commit fa partire i test su [Travis](https://travis-ci.org/studentisgss/booking); se li passa allora il codice viene inviato alla demo.

Con l'obiettivo di preparare una demo "presentabile" con il minor sforzo possibile, qual'è la cosa più importante da fare adesso?

**Comment by dtroletti** [comment]
Secondo me le cose più importanti sarebbero la schermata pubblica e magari la home page con il calendario navigabile (posso guardare io come fare) e la lista delle attività attive e passate.
Poi ci sarebbe la parte per effettuare le prenotazioni. Il login per ultimo.

**Comment by fpoli** [comment]
Possiamo partire dal calendario navigabile.

Mi sembra che la cosa più facile sia prendere la data dall'url (`?date=2016-03-03`) e visualizzare la relativa tabella html delle prenotazioni. Facciamo prima un prototipo di questo.

Se vediamo che il risultato è brutto (perchè la pagina nel ricaricarsi scompare per un istante ecc) possiamo cambiare il prototipo e fare le richieste in ajax come [l'attuale sito booking](https://booking.scuolagalileiana.unipd.it/prenotazioni/elenca).

**Comment by dtroletti** [comment]
Il link richiede l'autenticazione e quindi noi non possiamo accedere. Per il calendario io prendersi di farlo prima senza JS e in ogni caso poi di usare ajax per le richieste introducendolo dopo, così se qualcuno ha JS disattivato tutto funziona ancora.

**Comment by fpoli** [comment]
Sì, perfetto, stiamo dicendo la stessa cosa: prima facciamo la versione solo html + link, poi se serve ajax (il link era [questo](https://booking.scuolagalileiana.unipd.it/calendario)).

Se funziona anche senza js non è male, ma chi disabilità js lo fa con la consapevolezza che su tutti i siti qualcosa funzionerà peggio. Quindi non è una cosa che deve preoccuparci troppo. Per visualizzare un calendario "carino", per esempio, credo che dovremo usare js per forza.

**Comment by dtroletti** [comment]
Un paio di domande:
1) Nell'agenda gli eventi da visualizzare sono tutti o solo i futuri?
2) In events/urls.py nell'url dell'agenda c'è un parametro "url_parameter" definito ma non mi sembra serva a nulla. Bisogna eliminarlo?

**Comment by fpoli** [comment]
1) Possiamo fare come il sito booking attuale, in cui si sceglie il giorno degli eventi dal calendario? (anche i giorni passati). O forse sto confondendo le pagine? Non ricordo se calendario e agenda sono pagine distinte.
2) Si può eliminare. Credo che sia un residuo del copia-incolla di uno degli esempi

**Comment by dtroletti** [comment]
Calendario e agenda sono pagine distinte, l'agenda è il semplice elenco. Per il secondo punto ci penso io.

**Comment by fpoli** [comment]
1) Ho controllato, agenda e calendario sono distinti. Per l'agenda direi di visualizzare solo gli eventi presenti-futuri. Magari usando la paginazione se sono tanti (50 per pagina, nell'url l'id del primo). In futuro, se dovesse essere facile, andando alle pagine precedenti potremmo visualizzare gli eventi passati.

**Comment by dtroletti** [comment]
Prima versione senza l'uso di ajax, in settimana ci lavoro e lo aggiungo. Inoltre aggiungerò un link alle attività. Per ora come va?

**Comment by fpoli** [comment]
Ho visto, va benissimo. Fai pure il merge su master per questo tipo di risultati, le branch le terrei per lavori molto lunghi o lasciati a metà. Noi tendenzialmente faremo tanti piccoli lavoretti. (Aggiungo un link e faccio io il merge).

**Comment by dtroletti** [comment]
Ora ho guardato per la paginazione con Django per l'agenda ed è veloce da fare. Ci lavoro.

**Comment by dtroletti** [comment]
Restano da fare tra le altre cose:
1. Lista delle attività presenti e passate
2. Pagina "pubblica" per il monitor
3. Sistemare grafica agenda
Chi vuole farlo?

**Comment by dtroletti** [comment]
Per il punto uno guardate anche #12

**Comment by fpoli** [comment]
Ho mandato il link della demo alla segreteria, chiudo questa issue e ne apriamo di nuove per le cose che rimangono da fare
