### ISSUE TITLE
Errore url /events/agenda/

### ISSUE THREAD

**Issue by fpoli** [studentisgss/booking#16]
Aprendo l'url `/events/agenda/` (https://demo-sgss.rhcloud.com/events/agenda/) viene mostrato un messaggio di errore. Dovrebbe invece visualizzare la pagina 1, come default.

**Comment by dtroletti** [comment]
Va omesso "/" alla fine, comunque usando il template tag url o la funzione reverse nelle view un url come quello non dovrebbe aprire. Nel caso di volesse l'url in quel modo posso farla accettare.

**Comment by fpoli** [comment]
Tutto ok, ho scoperto che era colpa del mio Chrome: cliccando sul link "Agenda" mi aggiungeva automaticamente una `/` alla fine... cancellando i cookie si è risolto (boh).
