### ISSUE TITLE
Aggiungere più eventi alla demo

### ISSUE THREAD

**Issue by fpoli** [studentisgss/booking#18]
Bisognerebbe aggiungere più eventi al file `/fixtures/events.json`, fino ad averne qualche centinaio distribuiti lungo tutto il 2016.

Un programmino per generarli automaticamente sarebbe l'ideale, a patto che gli eventi siano verosimili (niente prenotazioni nel wekend, non sempre lo stesso giorno ecc) e che non ci siano sovrapposizioni.

**Comment by dtroletti** [comment]
Sto scrivendo un programma per generare casualmente gli eventi, posso aggiungere più attività con `important=True`?
Inoltre il campo important  lo lasciamo così o lo cambiano in archived?

**Comment by fpoli** [comment]
Ok, metti pure "important=true" ad un po' di attività. Secondo me possiamo rinominarlo in "archived", sentiamo anche gli altri.

**Comment by albesianor** [comment]
Anche secondo me si può rinominare "archived"

2016-04-07 16:28 GMT+02:00 Federico notifications@github.com:
