### ISSUE TITLE
Creare pagina per gli avvisi

### ISSUE THREAD

**Issue by fpoli** [studentisgss/booking#21]
Creare degli avvisi (news) per la demo:
- creare il file in `fixtures/news.json` (es. `fixtures/activities.json`)
- aggiungere la corrispondente riga a `Makefile`. Eseguendo `make reset-db` nel terminale dovrebbe caricare automaticamente nel db i dati.

Creare una pagina per visualizzare le news:
- scrivere una "view" in `news/views.py` (es. `activities/views.py`)
- scrivere un template `news/templates/news/list.html` per la pagina da visualizzare (es.  `activities/templates/activities/agenda.html`)
- aggiungere l'url della pagina a `news/urls.py` (es. `events/urls.py`)
- aggiungere un link alla pagina delle notizie nel menu (trova tu il file :wink: )

**Comment by fpoli** [comment]
https://github.com/studentisgss/booking/wiki/Tutorial%3A-la-prima-issue

**Comment by fpoli** [comment]
`python3 ./manage.py createsuperuser` per creare un utente admin

`python3 ./manage.py runserver` per far partire il server in locale

**Comment by FedericoSold** [comment]
`activities/templates/activities/agenda.html` si chiama `detail.html`. 
E' un problema o un errore di battitura?

**Comment by dtroletti** [comment]
L'agenda si trova in events non in activities, la pagina a cui tu ti stai riferendo penso sia il dettaglio degli eventi per una singola attività.

**Comment by fpoli** [comment]
Si, ho sbagliato il nome del file. "detail.html"  va benissimo
