### ISSUE TITLE
Pagina "pubblica" per il monitor

### ISSUE THREAD

**Issue by fpoli** [studentisgss/booking#23]
Preparare la pagina "pubblica" per il monitor, tipo https://booking.scuolagalileiana.unipd.it/schermata

**Comment by albesianor** [comment]
Ho fatto una prima bozza di pagina del monitor
http://demo-sgss.rhcloud.com/events/monitor
Come potete vedere ricalca da lontano la pagina attuale, anche se è parecchio semplificata rispetto ad essa.
La colonna sulla sinistra è dedicata agli eventi, mentre quella sulla destra dovrebbe essere per le news (al momento è una colonna vuota).
Pensavo di continuare appunto su quest'ultima colonna ed implementare la visualizzazione delle news.
Fatemi sapere che cosa ve ne pare: se avete miglioramenti/suggerimenti sono ovviamente ben graditi.

**Comment by albesianor** [comment]
Aggiunti gli avvisi

**Comment by dtroletti** [comment]
Due cose:
1. Penso ci sia un piccolo errore: "<table d="table_events">"
2. Io ingrandirei e separerei maggiormente il titolo "Prenotazioni ..." dal resto.

**Comment by dtroletti** [comment]
Il testo mancante è: table d="table_events"

**Comment by fpoli** [comment]
Sul monitor credo che sia meglio visualizzare soltanto le aulee "importanti". Siete dello stesso parere?

**Comment by albesianor** [comment]
Intendi quelle del Morgagni?

**Comment by fpoli** [comment]
Mi riferivo alle aule con flag `important`, che poi immagino saranno esattamente quelle del Morgagni

**Comment by dtroletti** [comment]
@albesianor ti va bene se lavoro un po' anche io sulla grafica della pagina?

**Comment by albesianor** [comment]
Certo, non c'era nemmeno bisogno di chiedere

**Comment by dtroletti** [comment]
Ho fatto qualcosa, è un po' da sistemare perché si perdono eventi se ce ne sono troppi. Una cosa da fare forse sarebbe ridurre l'altezza delle immagini.

Nella schermata del monitor mostriamo tutte le aule o solo quelle `important`, cioè quelle del Morgagni?

**Comment by fpoli** [comment]
Solo le aule `important`, sì. Metteremo il flag in modo che siano quelle del Morgagni, sì.

**Comment by dtroletti** [comment]
Piccolo test:
![monitor](https://cloud.githubusercontent.com/assets/15255588/15548701/e985ef10-22a9-11e6-9a9d-b351b51019fa.jpg)

Da quello che ho visto servirebbe di ingrandire ancora un po' il testo e migliorare il footer (quel marrone non sta troppo bene).

**Comment by albesianor** [comment]
Secondo me il footer si può togliere del tutto, così da rendere un po' più
leggera la lettura della pagina (secondo me ingombra soltanto)

2016-05-25 19:04 GMT+02:00 Daniele Troletti notifications@github.com:

**Comment by fpoli** [comment]
Sono d'accordo sul togliere del tutto il footer. Abbiamo uno schermo gigante e buona parte fa solo da cornice per le informazioni...

Potremmo anche togliere i margini destro e sinistro, lasciando tutto lo spazio al testo (ingrandito un po').

**Comment by dtroletti** [comment]
Per il footer fatto, per i margini laterali mi sembra che la pagina perda troppo, li sto riducendo. A breve i commit.

**Comment by dtroletti** [comment]
Fatemi sapere com'è. Spero di non aver esagerato con la dimensione del testo.

**Comment by dtroletti** [comment]
Altri due test, effettivamente non sta male neanche eliminando del tutto i margini, fatemi sapere cosa preferite, se la prima o la seconda. (Chiedo scusa per la scarsa qualità)

![1](https://cloud.githubusercontent.com/assets/15255588/15575802/08c240e4-2355-11e6-9a15-bcbf8f96018a.jpg)
![2](https://cloud.githubusercontent.com/assets/15255588/15575803/08c3d7d8-2355-11e6-8c70-3d90ade0664c.jpg)

**Comment by fpoli** [comment]
Voto la seconda, senza margini :) Però aggiungerei un padding di `1em` al riquadro bianco contenente gli avvisi e le prenotazioni. (Appena ho un po' di tempo lo faccio).

**Comment by dtroletti** [comment]
Questa era improvvisata al momento, modifica la classe side-shadow per
eliminare margin e padding.

**Comment by albesianor** [comment]
Voto anch'io la seconda, ma aggiungendo un po' di spazio bianco tra il
bordo sinistro dello schermo e il testo delle prenotazioni (altrimenti è
troppo schiacciato)

2016-05-26 16:10 GMT+02:00 Daniele Troletti notifications@github.com:

**Comment by dtroletti** [comment]
Stasera lo sistemo.

**Comment by dtroletti** [comment]
Ora dovrebbe essere a posto.

**Comment by dtroletti** [comment]
Ecco ora:

![monitor](https://cloud.githubusercontent.com/assets/15255588/16057772/cffb69c6-327b-11e6-8c74-9527fb4617c4.jpg)

**Comment by fpoli** [comment]
Ok :+1: Se anche secondo voi va bene possiamo chiudere la issue

**Comment by dtroletti** [comment]
Va bene, quindi chiudo.
