### ISSUE TITLE
Controllare vincoli nei modelli

### ISSUE THREAD

**Issue by fpoli** [studentisgss/booking#25]
Bisogna implementare nei modelli dei controlli per assicurarsi che nel database siano sempre rispettati i seguenti vincoli.
1. Per ogni aula (`rooms`) non possono esserci due o più prenotazioni sovrapposte (`events`) con stato "approvato" (`Events.APPROVED`) o "in attesa" (`Events.WAITING`). Quelle rifiutate non contano. Un'attività può avere eventi sovrapposti, basta che non siano riferiti alla stessa aula.
2. Qualsiasi evento deve avere la data-ora di inizio e di fine nello stesso giorno. Non possono esserci eventi a cavallo della mezzanotte, ma potrebbero (in via teorica) esserci eventi che cominciano esattamente a mezzanotte e/o che finiscono esattamente a mezzanotte.
3. `start_date` deve precedere `end_date`, e non possono essere uguali.

**Comment by fpoli** [comment]
Usiamo questo: https://docs.djangoproject.com/en/1.8/ref/models/instances/#validating-objects

**Comment by dtroletti** [comment]
Vedi: b4430cc82649bf7780150a4c867f7009d510361d
Test: 5e1bbd74f7b5e262c035a919b93f8df0f0a9eb35

Bisogna completare i test

**Comment by fpoli** [comment]
Mi sembra che sia a posto questa issue. Aggiungo qualche commento ai test e poi la chiudo
