### ISSUE TITLE
Preparare il file con la traduzione

### ISSUE THREAD

**Issue by fpoli** [studentisgss/booking#27]
Nei file `.py` usiamo l'inglese, ma nelle pagine di amministrazione vogliamo visualizzare i messaggi in italiano.

Se è una cosa facile, ci sarebbe da preparare il file `.po` con la traduzione in italiano dei messaggi.

**Comment by dtroletti** [comment]
Ora i messaggi già scritti sono tradotti, manca da controllare se qualcosa d'altro va tradotto.
Scrivo sulla wiki come fare.

**Comment by dtroletti** [comment]
Volendo si potrebbero tradurre anche in inglese le scritte statiche nelle pagine (non il contenuto che viene dal DB), che potrebbe essere utile per eventuali studenti stranieri che non capiscono ancora bene l'italiano.

**Comment by dtroletti** [comment]
Pagina della wiki: https://github.com/studentisgss/booking/wiki/Traduzione-dei-testi

**Comment by fpoli** [comment]
Ottimo! I testi dei template, però, li teniamo in italiano. Per adesso non ne varrebbe la pena, ci distrarrebbe soltanto dalle cose importanti. (Teniamo solo il testo nei file `.py` in inglese).

Le istruzioni della wiki si riferiscono alla modifica delle traduzioni esistenti o alla loro prima creazione? Forse questo sarebbe meglio chiarirlo.

**Comment by dtroletti** [comment]
Spero così sia più chiaro.

**Comment by dtroletti** [comment]
Per ora ho provato con il model di events ed è piuttosto rapido, a breve faccio anche gli altri.
