### ISSUE TITLE
Sistemare validazione html avvisi

### ISSUE THREAD

**Issue by dtroletti** [studentisgss/booking#29]
Vedi https://validator.w3.org/nu/?doc=http%3A%2F%2Fdemo-sgss.rhcloud.com%2Fnews%2F

**Comment by FedericoSold** [comment]
Ho sostituito due `div` con `span` mentre il terzo che dava problemi l'ho sostituito con `nav`. 
Non è perfetta come soluzione ma non ho trovato nulla di meglio.
Avete qualche consiglio?

**Comment by FedericoSold** [comment]
Come posso "testare" il codice che sta ancora solo nel mio computer?

**Comment by dtroletti** [comment]
Se per testare il codice intendi validare l'html devi aprire nel browser la pagina che vuoi controllare, copiare tutto l'html della pagina usando gli strumenti di sviluppo e poi incollarlo nell'apposito campo di [questo sito](https://validator.w3.org/nu/#textarea), a questo punto premi `check` e ottieni l'esito.

**Comment by FedericoSold** [comment]
Grazie.

**Comment by fpoli** [comment]
La prima delle risposte a questo link mi sembra possa andare bene:
https://stackoverflow.com/questions/19236717/how-to-make-a-bootstrap-accordion-collapse-when-clicking-the-header-div

Per rendere tutta la barra grigia cliccabile senza dover usare un mega tag `<a>` spiegano che basta aggiungere al `div`o `h4` del titolo gli attributi

```
data-toggle="collapse"
data-target="#ElementToExpandOnClick"
```

Credo che la cosa migliore sia utilizzare la loro tecnica e allo stesso tempo tenere l'attuale tag `<a>` solo attorno al titolo dell'avviso (la colonna di sinistra), per assicurarsi che funzioni anche da cellulare (nei commenti dicono che non funziona su iPhone...)

**Comment by fpoli** [comment]
Come è adesso va benissimo, chiudo
