### ISSUE TITLE
Creare home page

### ISSUE THREAD

**Issue by Agno94** [studentisgss/booking#3]
Pensavamo che nella prima pagina ci potessero stare:
- gli avvisi (news)
- qualcosa tipo la situazione attuale (o nel breve futuro ??) delle aule
- tasto login

**Comment by reptencyd** [comment]
Fare riferimento allo schema che verrà caricato in #6.

**Comment by fpoli** [comment]
Ora le cose essenziali dovrebbero esserci. Gli avvisi li lasciamo nella loro pagina e per il login vedremo in futuro, chiudo perchè per adesso non sono urgenti
