### ISSUE TITLE
Nascondere messaggio demo

### ISSUE THREAD

**Issue by fpoli** [studentisgss/booking#34]
Il messaggio "Questo sito è una DEMO in continuo sviluppo." dovrebbe essere assente se nella configurazione `settings.py` è stata impostata la variabile `DEMO = False`.

**Comment by dtroletti** [comment]
Bisogna mettere un if nel template di base, problema: bisogna passargli il valore della variabile `DEMO` contenuta in `settings.py`. Quindi o gli viene passato da tutte le view (**NO!**) o creiamo una view da cui facciamo ereditare tutte le altre view oppure creiamo un context processor.

(http://stackoverflow.com/questions/433162/can-i-access-constants-in-settings-py-from-templates-in-django,
http://stackoverflow.com/questions/12166537/django-settings-py-variables-in-templates)

**Comment by fpoli** [comment]
Mmm... Piuttosto, aggiungiamo allo script di deploy della demo un comando per inserire quel messaggio nel file del template. Le altre soluzioni mi sembrano troppo complicate. (Ora che ricordo, avevo cercato anche io un po' di tempo fa come fare ed ero arrivato alle stesse tue conclusioni).

**Comment by dtroletti** [comment]
L'uso del context processor non mi sembra così complicato ed è quello che prevederebbe la minor modifica di codice.
Per quanto riguarda aggiungere allo script di deploy il comando si potrebbe mettere il messaggio commentato con `{% comment "DEMO" %}<li>...</li>{% endcomment %}` e poi usare
`sed -i "s/{% comment \"DEMO\" %}//g" layout.html`
`sed -i "s/{% endcomment %}//g" layout.html`
nello script (magari un `make demo` che controlla tutti i file dei template).
Fammi sapere che procedo.

**Comment by dtroletti** [comment]
Ho provato con il context processor e sono due righe di codice e funziona bene. Se va bene anche a voi lo carico. Fatemi sapere.

**Comment by fpoli** [comment]
Ok, se ce l'hai già pronto per me possiamo provare ad usarlo (su master)

**Comment by dtroletti** [comment]
Se la soluzione va bene io chiuderei la issue.

**Comment by fpoli** [comment]
Per me è ok
