### ISSUE TITLE
Messaggio non ci sono avvisi

### ISSUE THREAD

**Issue by fpoli** [studentisgss/booking#36]
La pagina avvisi, se non ci sono avvisi nel database, dovrebbe visualizzare un messaggio del tipo "Non ci sono avvisi".

**Comment by FedericoSold** [comment]
Se volte posso provarci io DOPO LA SESSIONE.

**Comment by fpoli** [comment]
Ah, certamente, era sottointeso :+1:
Ieri mi sono trovato con Daniele per installare un po' di cose sul server, e ne ho approfittato per segnarmi con le issue cosa manca. Non c'è fretta per chiuderle.

**Comment by FedericoSold** [comment]
Ora se non ci sono avvisi appare la scritta "Non ci sono avvisi". La pagina resta comunque spoglia.
