### ISSUE TITLE
Pagine personalizzate per errori 404 e 500

### ISSUE THREAD

**Issue by fpoli** [studentisgss/booking#40]
Attualmente in caso di errore del server o di pagina mancante viene visualizzato il messaggio di errore di default. Sarebbe meglio avere una pagina di errore personalizzata: con il menu del sito, una descrizione dell'errore in italiano e un link alla homepage del sito.

**Comment by dtroletti** [comment]
Piccolo problema: Flake8 mi segnala degli errori ma il codice che da problemi è quello che deve essere usato secondo la guida di django e che funziona.

```
$ make linter
=== Pep8 ===
=== Flake8 ===
./booking/urls.py:37:1: F811 redefinition of unused 'handler404' from line 16
./booking/urls.py:38:1: F811 redefinition of unused 'handler500' from line 16
make: *** [linter] Error 1
```

Aggiungiamo anche F811 da ignorare o avete altre idee?

**Comment by fpoli** [comment]
Secondo me possiamo aggiungerlo agli ignorati, non è un nostro errore

**Comment by dtroletti** [comment]
Aggiunti il file della licenza, in fondo per quella delle immagini.
Fatemi sapere se va bene.

**Comment by fpoli** [comment]
Credo che vada bene, ma non sono un avvocato :smile:. Se mai qualcuno dovesse segnalarci qualcosa possiamo cambiare immagini o correggere il modo in cui è espressa la licenza
