### ISSUE TITLE
Rendere opzionale la descrizione delle attività?

### ISSUE THREAD

**Issue by fpoli** [studentisgss/booking#41]
Per le attività sembra che il campo `descrizione` sia obbligatorio. Non è meglio se lo rendiamo opzionale?

**Comment by albesianor** [comment]
Secondo me sì

2016-07-08 13:30 GMT+02:00 Federico notifications@github.com:

**Comment by fpoli** [comment]
(promemoria) Per fare la modifica anche sul database di produzione dovremo cominciare ad usare le [migrazioni](https://docs.djangoproject.com/en/1.8/topics/migrations/). Django fa quasi tutto in automatico, ma fino ad ora ne abbiamo fatto a meno perchè non ci servivano.

**Comment by dtroletti** [comment]
Descrizione resa opzionale aggiungendo al campo `blank = True` nel commit 03fe6e8. Nel database viene salvata una stringa vuota e non `NULL` quindi non serve apportare alcuna modifica.
