### ISSUE TITLE
Pannello Morgagni

### ISSUE THREAD

**Issue by FedericoSold** [studentisgss/booking#49]
Visualizzare anche le lezioni in aule non del Morgagni, magari dividendo la pagina in due sezioni in verticale come "Collegio Morgagni" e "Altre Aule".

Se gli eventi sono troppi si dovrebbe usare una forma di paginazione che ruoti in automatico.

**Comment by dtroletti** [comment]
Creata pull request #56.

**Comment by dtroletti** [comment]
Pull request chiusa.
