### ISSUE TITLE
Gestione attvità e eventi

### ISSUE THREAD

**Issue by FedericoSold** [studentisgss/booking#52]
Pagine per la gestione delle attività e degli eventi, si arriva dai pulsanti sulla pagina delle attività "Crea nuova" e "modifica". Possono vedere queste pagine solo gli utenti loggati i cui gruppi hanno il permesso `booking.can_book_room`.

Consiste in:
- Pagina con i dati modificabili dell'attività e elenco modificabile degli eventi
- Pagina di conferma prenotazione con avviso di quelle in attesa di approvazione

Se l'utente può si prenota subito l'aula, altrimenti si mette l'evento in "attesa" che venga confermato.

**Comment by dtroletti** [comment]
Creata pull request #57.

**Comment by dtroletti** [comment]
Pull request chiusa.
