### ISSUE TITLE
Aggiornamento Django

### ISSUE THREAD

**Issue by dtroletti** [studentisgss/booking#54]
Guardando per la gestione del login e dei permessi ho visto che nella versione 1.9 ci sono stati molti miglioramenti che potrebbero ridurre significativamente il codice da scrivere e lo migliorerebbero molto: https://docs.djangoproject.com/en/1.10/topics/auth/default/#the-loginrequired-mixin

Guardando anche le release notes di questa versione ho trovato queste tre cose interessanti:
https://docs.djangoproject.com/en/1.10/releases/1.9/#password-validation
https://docs.djangoproject.com/en/1.10/releases/1.9/#permission-mixins-for-class-based-views
https://docs.djangoproject.com/en/1.10/releases/1.9/#tests (in particolare force_login())

Io valuterei quindi di aggiornare django dalla 1.8 attualmente usata alla 1.9, non ho trovato miglioramenti importanti per noi nella 1.10 (ultima) e quindi non penserei di aggiornare a quella.

Voi cosa ne dite?
@albesianor @FedericoSold

**Comment by FedericoSold** [comment]
Sembra utile per me va bene aggiornare alla 1.9. Ma cosa comporta aggiornare la versione di Django, immagino che il codice che abbiamo scritto rimanga compatibile, si potrebbero verificare dei conflitti o degli errori dovuti alla compatibilità?

**Comment by dtroletti** [comment]
Secondo me dovrebbe essere tutto compatibile, se va bene anche a @albesianor lo aggiorno e sistemo eventuali incompatibilità.

**Comment by dtroletti** [comment]
Aggiorno direttamente sul master.

**Comment by dtroletti** [comment]
Django aggiornato nel commit cc83d4c.
