### ISSUE TITLE
Modificare i model attività

### ISSUE THREAD

**Issue by FedericoSold** [studentisgss/booking#64]
- [x] aggiungere nel model i campi classe e professori
- [x] implementare una funzione per il titolo (es. SN - Titolo (Nome Professore))
- [x] modificare i template per usare la funzione precedente al posto di title
- [x] ordinare attività negli elenchi per classe e poi per titolo
- [x] adattare la tabella "Tutte le attività" con i nuovi campi
- [x] modificare le pagine di inserimento e modifica delle attività
- [x] rendere la tabella ordinabile con Javascript

Le classi devono essere SN SM SS e altro. Con altro omettere il nome della classe nella funzione precedente.

**Comment by dtroletti** [comment]
Aperta pull request #75
