### ISSUE TITLE
Feed RSS

### ISSUE THREAD

**Issue by FedericoSold** [studentisgss/booking#69]
- [x] Per ogni attività creare un feed RSS indipendente

Il feed contiene il nome del corso, aula, orario e un collegamento all'evento.

**Comment by dtroletti** [comment]
Facile usando https://docs.djangoproject.com/en/1.11/ref/contrib/syndication/

Titolo: titolo attività
Descrizione: aula - orario
Link: link al dettaglio attività

URL per il feed /activities/feed/<id_activity> e poi si filtra sull'id dell'attività.

**Comment by dtroletti** [comment]
Mettere in ogni feed anche gli avvisi attivi il giorno. E creare un feed solo per gli avvisi.
