### ISSUE TITLE
 Template comune a più modelli

### ISSUE THREAD

**Issue by reptencyd** [studentisgss/booking#7]
Si vorrebbe creare un template di base estendibile da altri template dentro modelli diversi.
Possibili soluzioni:
- Mettere il template di base in un modello e chiamarlo da altri template in altri modelli.
- Vedere la documentazione

**Comment by fpoli** [comment]
Mi sembra che una buona soluzione sia http://stackoverflow.com/questions/4571686/django-include-template-from-another-app.
In pratica, una app chiamata "base" contenente i template condivisi.

**Comment by dtroletti** [comment]
In particolare lì si parla di include, a noi serve usare extend

**Comment by fpoli** [comment]
Sì la domanda è sull'include, ma la prima risposta mi sembra che funzioni bene anche per l'extend.

**Comment by fpoli** [comment]
La tecnica dell'applicazione `base` funziona, chiudo la domanda
