### ISSUE TITLE
Prenotazione aule con calendario

### ISSUE THREAD

**Issue by FedericoSold** [studentisgss/booking#73]
- per ogni attività, quattro campi in una stessa finestra: aula, ora inizio, ora fine, calendario
- cambiando aula e orario cambiano i giorni selezionabili sul calendario, in accordo con le disponibilità
- si possono selezionare più giorni dallo stesso calendario
- un apposito pulsante "Aggiungi" permette di creare eventi per l'aula selezionata, all'orario selezionato, nei giorni scelti
- sotto i quattro campi summenzionati, il riepilogo di tutte gli eventi, con un pulsante per rimuoverli
- (extra) passando il mouse sui giorni del calendario compare una finestrella che mostra in quali orari del giorno sono prenotati
![photo6035144025952070403](https://user-images.githubusercontent.com/15311844/32197982-9b2b4892-bdc6-11e7-8d98-062d9b1f62f5.jpg)

**Comment by dtroletti** [comment]
Ora è già funzionante, manca solo la parte extra che devo vedere se è fattibile.
Ho verificato, entro domani aggiungo anche l'altra parte.

**Comment by dtroletti** [comment]
Purtroppo il plugin (JQuery tooltip) non funziona come dovrebbe: non riesco a far apparire in nessun modo il tooltip. C'è ma per farlo apparire bisogna togliere e rimettere il cursore.
Non funziona nè usando 'open' nè chiamando da codice gli eventi che dovrebbero attivarlo.
Cosa consigliate di fare? Lascio così o elimino questa parte?

**Comment by albesianor** [comment]
Io lascerei così. Poi se troviamo un modo per farlo funzionare lo aggiustiamo, ma intanto la funzionalità c'è.

**Comment by dtroletti** [comment]
In attesa della chiusura di #70 così da restringere i giorni prenotabili secondo le restrizioni.

**Comment by dtroletti** [comment]
Sistemati tooltip, ora appaiono correttamente. Attendo la chiusura di #70 per aggiungere anche le restrizioni.
