### ISSUE TITLE
Aggiungere modelli e Readme

### ISSUE THREAD

**Issue by fpoli** [studentisgss/booking#8]
Apro questa issue per permettere a chi non era alla riunione di seguire i lavori "in corso".
- [x] Aggiungere i "vecchi" modelli al repository, spezzandoli nelle varie app
- [ ] Aggiungere il contenuto del "vecchio" Readme al repository

**Comment by dtroletti** [comment]
Aggiunti i vecchi model nel commit aa49d3e4b76fa12261ba5df67de9eda98d504f4d
