### ISSUE TITLE
Linee guida

### ISSUE THREAD

**Issue by albesianor** [studentisgss/booking#80]
Dovremmo preparare un documento in cui riassumiamo il funzionamento di booking e spieghiamo il modo corretto di usarlo. Servirebbe sia ai rappresentanti che alla segreteria.

**Comment by lzampieri** [comment]
[Qui](https://docs.google.com/document/d/1_btY2HM4Rc6tUaqrAovioS68toOat__pA-Hnl9ElcwM/edit?usp=sharing)
