### ISSUE TITLE
Unificate lista attività

### ISSUE THREAD

**Issue by dtroletti** [studentisgss/booking#87]
Al momento la lista delle attività non archiviate e tutte sono distinte come template.
Unificare questi due template usando degli `{% if %}` per mostrare i messaggi giusti in base a cosa si sta visualizzando (usare un parametro nel context).

Usare la view per il caso generale e creare una classe che eredita dalla precedente per la view delle sole attività non archiviate: se in quella principale in `context["x"]` ci sono tutte le attività basterà fare `context["x"] = context["x"].filter(...)` e far ritornare il parametro che indica che si stanno visualizzando solo le attività non archiviate.

**Comment by lzampieri** [comment]
Nell'unificare la lista delle attività si sono evidenziati due nuovi problemi da risolvere:

- [ ] Sistemare grafica pulsante "Cancella ricerca"
- [ ] Scrivere paginazione in Javascript

**Comment by dtroletti** [comment]
Esegui un push delle modifiche che hai fatto così possiamo vedere dove sei e aiutarti meglio.
Se serve la paginazione posso fartela io.
