### ISSUE TITLE
Cambiare grafica pagina avvisi

### ISSUE THREAD

**Issue by FedericoSold** [studentisgss/booking#88]
Rendere la pagina avvisi simile alla nuova pagina per le aule.
Usare il primo esempio in [questa pagina](https://getbootstrap.com/docs/4.0/components/collapse/). Assicurarsi che i titoli, le date e gli eventuali pulsanti siano incollonati uno sopra l'altro stile tabella.
Adattare il javascript.

**Comment by dtroletti** [comment]
Proposta per la nuova grafica: d2a516503a121ac0d6a7cc6b2c27dfe3b2c7a54f.
