### ISSUE TITLE
App `base`

### ISSUE THREAD

**Issue by fpoli** [studentisgss/booking#9]
- [x] Creare l'app `base`
- [x] Scrivere un template di base `/base/templates/base.html`

L'app `base` sarà quella che conterrà il template di base e il file `url.py` per la url `r'^$'` del sito.
Ad esempio, come hanno fatto in https://github.com/xenith/django-base-template/tree/master/base.

**Comment by dtroletti** [comment]
Nella directory templates salviamo i files direttamente o in /"nome app"/file.html come suggerisce anche la documentazione di django per evitare di avere due template con lo stesso nome? Io sarei per la seconda.

**Comment by fpoli** [comment]
Anche secondo me la seconda è molto meglio.

**Comment by dtroletti** [comment]
Creo un branch app_base e inizio a lavorarci.

**Comment by fpoli** [comment]
:+1: Se vuoi anche aprire la pull request commentiamo da lì
